### ISSUE TITLE
Build fail on Jenkins due to Javascript out of heap

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-client#84]
# Context
Build fails on Jenkins due to Javascript heap (and possibly other things, such as node-sass).
The mock package from fedora creates a mocked environment. This is missing the python2 package needed for pulling in node-sass bind to build the RPM.

```
Using nspawn with args ['--capability=cap_ipc_lock', '--bind=/tmp/mock-resolv.cfcqrlft:/...skipping...
gyp verb `which` failed Error: not found: python2
...skipping...
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builddir/build/BUILD/digital-paper-edit-client/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builddir/build/BUILD/digital-paper-edit-client/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builddir/build/BUILD/digital-paper-edit-client/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builddir/build/BUILD/digital-paper-edit-client/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:13:12)\n    at F (/builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:68:19)\n    at E (/builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:80:29)\n    at /builddir/build/BUILD/digital-paper-edit-client/node_modules/which/which.js:89:16\n    at /builddir/build/BUILD/digital-paper-edit-client/node_modules/isexe/index.js:42:5\n    at /builddir/build/BUILD/digital-paper-edit-client/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
```
 
# Acceptance Criteria
Build succeeds and digital-paper-edit int tools has a new version of the client RPM.

# Additional Context
https://fedoraproject.org/wiki/Using_Mock_to_test_package_builds#Building_packages_that_depend_on_packages_not_in_a_repository
https://jenkins.newslabs.tools.bbc.co.uk/job/digital-paper-edit-client/36/console

**Comment by emettely** [comment]
Possibly network issues:
```
...skipping...
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/builddir/build/BUILD/digital-paper-edit-client/node_modules/node-gyp/lib/install.js:197:21)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestError (/builddir/build/BUILD/digital-paper-edit-client/node_modules/request/request.js:881:8)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:324:9)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at TLSSocket.emit (events.js:188:7)
gyp ERR! stack     at connectErrorNT (net.js:1034:8)
gyp ERR! System Linux 3.10.0-1062.4.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/builddir/build/BUILD/digital-paper-edit-client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
```

**Comment by emettely** [comment]
The rebuild step that's in the SPEC file generated by speculate makes node-sass try to get a specific build from git, which the box may not have any connection to.

**Comment by emettely** [comment]
https://github.com/sass/node-sass

`node-sass` is only supported from Node v 8 and above.
The default Node version being used in `mock-build` is v 6.
The mock-build is a "VM" so it doesn't know about the surrounding environment (Jenkins with node 8) so we need to specify a `yum` config file in `mock-conf/nodesource-el7.repo` to allow the RPM to build with node 8 and run `mock-bulid --os 7 -r mock_conf`:

```
[nodesource]
name=Node.js Packages for Enterprise Linux 7 - $basearch
baseurl=https://rpm.nodesource.com/pub_8.x/el/7/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 7 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_8.x/el/7/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
```

**Comment by emettely** [comment]
https://github.com/bbc/digital-paper-edit-client/compare/d816b611a5050bb730f2b480d5cb52577176c062..master
